export const rankData = [
    { value: '이병' },
    { value: '일병' },
    { value: '상병' },
    { value: '병장' },
    { value: '하사' },
    { value: '중사' }, 
    { value: '상사' },
    { value: '원사' },
    { value: '준위' },
    { value: '소위' },
    { value: '중위' },
    { value: '대위' },
    { value: '소령' },
    { value: '중령' },
    { value: '대령' },
    { value: '준장' },
    { value: '소장' },
    { value: '중장' },
    { value: '대장' },
]